options:
  platform: psx
  basename: stnz0
  base_path: ..
  build_path: build/hd
  target_path: disks/pspeu/PSP_GAME/USRDIR/res/ps/hdbin/nz0.bin
  asm_path: asm/hd/st/nz0
  asset_path: assets/st/nz0
  src_path: src/st/nz0
  ld_script_path: build/hd/stnz0.ld
  compiler: GCC
  symbol_addrs_path:
    - config/symbols.hd.txt
    - config/symbols.hd.stnz0.txt
  undefined_funcs_auto_path: build/hd/config/undefined_funcs_auto.hd.stnz0.txt
  undefined_syms_auto_path: build/hd/config/undefined_syms_auto.hd.stnz0.txt
  find_file_boundaries: true
  use_legacy_include_asm: false
  migrate_rodata_to_functions: true
  asm_jtbl_label_macro: jlabel
  symbol_name_format: hd_$VRAM
  section_order:
    - .data
    - .rodata
    - .text
    - .bss
    - .sbss
  ld_bss_is_noload: false
  disasm_unknown: true
  disassemble_all: true
  ld_generate_symbol_per_data_segment: true
  global_vram_start: 0x80010000
sha1: 8975dfb26648a49445fe9c6ba47041ec8f92cd86
segments:
  - name: stnz0
    type: code
    start: 0
    vram:  0x80180000
    align: 4
    subalign: 4
    subsegments:
      - [0x0, data]
      - [0xA94, .data, e_init]
      - [0xD52, data]
      - [0xD8C, .data, e_red_door_tiles]
      - [0xDBC, data]
      - [0x13F0, .data, d_prize_drops]
      - [0x1406, c, hd]
      - [0x30068, .rodata, hd]
      - [0x303F4, c, e_room_bg]
      - [0x304BC, c, hd]
      - [0x30540, c, e_lock_camera]
      - [0x30988, c, e_breakable]
      - [0x30C5C, c, e_red_eye_bust]
      - [0x30D84, c, e_purple_brick]
      - [0x30F60, c, e_left_secret_room_wall]
      - [0x316B4, c, e_puzzle]
      - [0x31E50, c, e_cannon]
      - [0x32574, c, e_elevator2]
      - [0x32A74, c, e_nz0_room2]
      - [0x33B08, c, e_life_max_tank]
      - [0x33C80, c, e_blue_flame_table]
      - [0x34038, c, e_misc]
      - [0x340F8, c, e_explosion_puff_opaque]
      - [0x3448C, c, bossfight]
      - [0x34B50, c, slogra]
      - [0x35C38, c, gaibon]
      - [0x372A4, c, e_elevator]
      - [0x379DC, c, hd]
      - [0x37E50, c, cutscene]
      - [0x37E7C, c, hd]
      - [0x38128, c, cutscene]
      - [0x39268, c, maria]
      - [0x39930, c, st_update]
      - [0x39D64, c, collision]
      - [0x3B520, c, create_entity]
      - [0x3B814, c, hd]
      - [0x3BD7C, c, create_entity]
      - [0x3C098, c, hd]
      - [0x3C110, c, e_red_door]
      - [0x3CD48, c, st_common]
      - [0x3E1F8, c, hd]
      - [0x3E458, c, e_collect]
      - [0x3E534, c, hd]
      - [0x3E64C, c, e_collect]
      - [0x3E6F0, c, hd]
      - [0x3E768, c, e_collect]
      - [0x3F0D8, c, hd]
      - [0x3F17C, c, e_collect]
      - [0x40934, c, e_misc]
      - [0x42CD0, c, e_particles]
      - [0x43514, c, e_room_fg]
      - [0x439D8, c, hd]
      - [0x43AB4, c, e_bone_scimitar]
      - [0x4426C, c, hd]
      - [0x44468, c, e_axe_knight]
      - [0x4517C, c, e_bloody_zombie]
      - [0x4567C, c, hd]
      - [0x45838, c, e_bloody_zombie]
      - [0x461FC, c, hd]
      - [0x46294, c, e_skeleton]
      - [0x469FC, c, e_spittle_bone]
      - [0x47318, c, e_subweapon_container]
      - [0x47C28, c, e_blood_skeleton]
      - [0x48038, c, e_sealed_door]
      - [0x48DAC, c, prim_helpers]
      - [0x495DC, c, e_life_up]
      - [0x49E90, .bss, bss]
      - [0x49E90, sbss]
  - [0x4ABF8]
